version: '3'

services:
  dosiscalc_db:
    image: mongo:4.2.1-bionic
    container_name: dosiscalc_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_db:/data/db
  dosiscalc_web:
    container_name: dosiscalc_web
    restart: always
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_HCAPTCHA_SITE_KEY: '10000000-ffff-ffff-ffff-000000000001'
    environment:
      MONGODB_URI: mongodb://dosiscalc_db:27017/dosiscalc
      NEXTAUTH_URL: http://localhost:3001
      JWT_SECRET: "H0jqHSXXBvNFBMuIkmrdD509tY82DXeR"
      NEXTAUTH_SECRET: "TgB3bBg6qJIU3f4CSBsJ4f6NSKsYC56F"
      HCAPTCHA_SECRET_KEY: "0x0000000000000000000000000000000000000000"
      MAILGUN_API_KEY: "key-0000000000000000000000000000"
      MAILGUN_DOMAIN: "mg.example.es"
      MAILGUN_FROM: "notify@example.es"
